import { Header } from '@/components/Sections/Header/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Footer } from '@/components/Sections/Footer/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <main>
        {children}
        </main>
        <Footer/>
        </body>
    </html>
  )
}
